######################## default configuration ####################
# The base URL of your site (required). This will be prepended to all relative URLs.
baseURL = "https://htkhsh.github.io/"
# Title of your website (required).
title = "Hideaki Takahashi"
# Your theme name
# theme = ""
# Default time zone for time stamps
timeZone = "Asia/Tokyo"
# post excerpt
summaryLength = 10
# disable language
disableLanguages = []
hasCJKLanguage = true
# default language
defaultContentLanguage = 'en'
defaultContentLanguageInSubdir = false

########################### Services #############################
[services]
[services.googleAnalytics]
ID = '' # Add your Google Analytics ID if needed

########################## Permalinks ############################
[permalinks.page]
"pages" = "/:slugorcontentbasename/"

########################## Pagination ############################
[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

############################# Build ##############################
[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'

############################# Modules ############################
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

############################# Outputs ############################
[outputs]
home = ["HTML", "RSS", "WebAppManifest", "SearchIndex"]

############################# Imaging ############################
[imaging]
quality = 80
resampleFilter = "Lanczos"

############################ Caches ##############################
[caches]
[caches.images]
dir = ":resourceDir/_gen"
maxAge = "720h"

[caches.assets]
dir = ":resourceDir/_gen"
maxAge = "720h"

############################ Markup ##############################
[markup]
[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = 'monokai'
lineNumbersInTable = false

[markup.tableOfContents]
startLevel = 2
endLevel = 5
ordered = true

########################### Media types ###########################
[mediaTypes]
[mediaTypes."application/manifest+json"]
suffixes = ["webmanifest"]

########################### Output formats #######################
[outputFormats]
[outputFormats.SearchIndex]
mediaType = "application/json"
baseName = "searchindex"
isPlainText = true
notAlternative = true
